const fs = require('fs')
const BASE = 'c:\\Escritorio\\Pagina Web\\velqia\\'

// utils.ts
const utils = [
  "import type { Category } from '@/types'",
  "",
  "export function cn(...classes: (string | undefined | false | null)[]): string {",
  "  return classes.filter(Boolean).join(' ')",
  "}",
  "",
  "export function categoryLabel(category: Category): string {",
  "  const map: Record<Category, string> = {",
  "    naturaleza: 'Naturaleza',",
  "    ciudad: 'Ciudad',",
  "    playa: 'Playa',",
  "    gastronomia: 'Gastronomia',",
  "    cultura: 'Cultura',",
  "    aventura: 'Aventura',",
  "    relax: 'Relax',",
  "  }",
  "  return map[category]",
  "}",
].join('\n')

// filters.ts
const filters = [
  "import type { Escape, FilterState } from '@/types'",
  "",
  "export type SortOption = 'relevancia' | 'destacados'",
  "",
  "export function filterEscapes(escapes: Escape[], filters: FilterState): Escape[] {",
  "  return escapes.filter(e => {",
  "    if (filters.departureCity && e.departureCity !== filters.departureCity) return false",
  "    if (filters.durationNights !== null && !e.durationVariants.some(d => d.nights === filters.durationNights)) return false",
  "    if (filters.category && e.category !== filters.category) return false",
  "    return true",
  "  })",
  "}",
  "",
  "export function sortEscapes(escapes: Escape[], sort: SortOption): Escape[] {",
  "  if (sort === 'destacados') return [...escapes].sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0))",
  "  return escapes",
  "}",
  "",
  "export function getEscapeBySlug(escapes: Escape[], slug: string): Escape | undefined {",
  "  return escapes.find(e => e.slug === slug)",
  "}",
].join('\n')

// types/index.ts
const types = [
  "export type Category = 'naturaleza' | 'ciudad' | 'playa' | 'gastronomia' | 'cultura' | 'aventura' | 'relax'",
  "",
  "export interface FAQItem {",
  "  question: string",
  "  answer: string",
  "}",
  "",
  "export interface AccommodationRecommendation {",
  "  name: string",
  "  description: string",
  "  priceRange?: string",
  "  whyItFits: string",
  "  link?: string",
  "}",
  "",
  "export interface DurationVariant {",
  "  nights: number",
  "  title: string",
  "  summary: string",
  "  forWhom: string[]",
  "  whatToDo: string",
  "  whatNotToDo: string",
  "  verdict: string",
  "  accommodations: AccommodationRecommendation[]",
  "  tip: string",
  "  ctaText: string",
  "}",
  "",
  "export interface BudgetBreakdown {",
  "  transport: string",
  "  accommodation: string",
  "  food: string",
  "  activities: string",
  "  total: string",
  "}",
  "",
  "export interface AffiliateLinks {",
  "  trainSearch?: string",
  "  hotelSearch?: string",
  "  activities?: string[]",
  "}",
  "",
  "export interface Escape {",
  "  id: string",
  "  slug: string",
  "  title: string",
  "  subtitle: string",
  "  departureCity: string",
  "  location: string",
  "  heroImage: string",
  "  category: Category",
  "  tags: string[]",
  "  featured: boolean",
  "  overview: {",
  "    intro: string",
  "    bestFor: string[]",
  "    lessRecommendedFor: string[]",
  "  }",
  "  quickSummary: {",
  "    keys: string[]",
  "  }",
  "  durationVariants: DurationVariant[]",
  "  practical: {",
  "    items: { label: string; value: string }[]",
  "  }",
  "  editorial: {",
  "    howToGetThere: string",
  "    budgets: BudgetBreakdown",
  "    tickets: string",
  "    commonMistakes: string[]",
  "    weatherHot: string",
  "    weatherRainy: string",
  "    firstTimeAdvice: string",
  "    quickWeekendAdvice: string",
  "    closing: string",
  "    affiliateLinks?: AffiliateLinks",
  "  }",
  "  faq: FAQItem[]",
  "}",
  "",
  "export interface FilterState {",
  "  departureCity: string",
  "  durationNights: number | null",
  "  category: Category | null",
  "}",
].join('\n')

fs.writeFileSync(BASE + 'lib\\utils.ts', utils, 'utf8')
fs.writeFileSync(BASE + 'lib\\filters.ts', filters, 'utf8')
fs.writeFileSync(BASE + 'types\\index.ts', types, 'utf8')

console.log('utils.ts: OK', utils.split('\n').length, 'lines')
console.log('filters.ts: OK', filters.split('\n').length, 'lines')
console.log('types/index.ts: OK', types.split('\n').length, 'lines')
